#!/usr/bin/env python3
import argparse
import os
import struct
from typing import List, Tuple

import numpy as np


# -----------------------------
# Utilities: float/int <-> hex
# -----------------------------
def float_to_hex(f):
    """Convert a float32 to an 8-character hex string (big-endian)."""
    return "".join(f"{b:02x}" for b in struct.pack(">f", np.float32(f)))


def hex_to_float(hex_str):
    """Convert an 8-character hex string to float32."""
    return struct.unpack(">f", bytes.fromhex(hex_str))[0]


def _is_float_like(v):
    return isinstance(v, (float, np.floating))


def _is_int_like(v):
    return isinstance(v, (int, np.integer))


# -----------------------------
# MIF writers
# -----------------------------
def write_mif_file(filename, data, width=32, depth=None):
    """
    Write data to a MIF (Memory Initialization File) format.

    Parameters:
    - filename: output file path
    - data: numpy array or list/iterable of values (float32 or int32)
    - width: bit width of each entry (default 32 for float32)
    - depth: number of entries (auto-calculated if None)
    """
    values = data.flatten() if isinstance(data, np.ndarray) else list(data)
    if depth is None:
        depth = len(values)

    with open(filename, "w") as f:
        # Header
        f.write(f"-- Memory Initialization File (.mif)\n")
        f.write(f"-- Generated by Sienna Pipeline Test Vector Generator\n\n")
        f.write(f"WIDTH={width};\n")
        f.write(f"DEPTH={depth};\n\n")
        f.write(f"ADDRESS_RADIX=UNS;\n")
        f.write(f"DATA_RADIX=HEX;\n\n")
        f.write(f"CONTENT BEGIN\n")

        # Data
        for addr, val in enumerate(values):
            if _is_float_like(val):
                hex_val = float_to_hex(val)
            elif _is_int_like(val):
                hex_val = f"{int(val) & 0xFFFFFFFF:08x}"
            else:
                # attempt cast
                try:
                    if isinstance(val, str) and val.startswith("0x"):
                        hex_val = f"{int(val, 16) & 0xFFFFFFFF:08x}"
                    else:
                        hex_val = float_to_hex(np.float32(val))
                except Exception:
                    raise TypeError(f"Unsupported value type at index {addr}: {type(val)}")
            f.write(f"    {addr} : {hex_val};\n")

        f.write(f"END;\n")


def write_config_mif_from_items(filename, items: List[Tuple[str, int | float, str]], width=32):
    """
    Write a config MIF from an ordered list of (name, value, vtype) tuples.

    items: list[ (name: str, value: int|float, vtype: 'int'|'float') ]
           Floats are encoded as IEEE-754 float32 (big-endian) hex.
           Ints are written as 32-bit hex.
    """
    depth = len(items)
    with open(filename, "w") as f:
        f.write(f"-- Test Configuration File (.mif)\n")
        f.write(f"-- Generated by Sienna Pipeline Test Vector Generator\n\n")
        f.write(f"WIDTH={width};\n")
        f.write(f"DEPTH={depth};\n\n")
        f.write(f"ADDRESS_RADIX=UNS;\n")
        f.write(f"DATA_RADIX=HEX;\n\n")
        f.write(f"CONTENT BEGIN\n")

        for addr, (name, val, vtype) in enumerate(items):
            if vtype == "float":
                hex_val = float_to_hex(np.float32(val))
                human = f"{float(val):.6g}"
            else:
                hex_val = f"{int(val) & 0xFFFFFFFF:08x}"
                human = f"{int(val)}"
            f.write(f"    {addr} : {hex_val};  -- {name} = {human}\n")

        f.write(f"END;\n")


# -----------------------------
# Activation helpers
# -----------------------------
def activation_to_code(activation_type):
    """
    Convert activation function name to 2-bit control code.

    Encoding:
    - 00: Linear/None
    - 01: ReLU
    - 10: Sigmoid
    - 11: Tanh
    """
    mapping = {
        "none": 0b00,
        "linear": 0b00,
        "relu": 0b01,
        "sigmoid": 0b10,
        "tanh": 0b11,
    }
    return mapping.get(activation_type.lower(), 0b01)


def apply_activation(x, activation_type="relu"):
    """Apply activation function element-wise."""
    if activation_type == "relu":
        return np.maximum(0, x)
    elif activation_type == "sigmoid":
        return 1 / (1 + np.exp(-np.clip(x, -500, 500)))
    elif activation_type == "tanh":
        return np.tanh(x)
    elif activation_type == "none":
        return x
    else:
        return x


# -----------------------------
# MaxPool & Dropout (golden)
# -----------------------------
def apply_maxpool_2d(
    input_matrix, pool_h=2, pool_w=2, stride_h=None, stride_w=None, padding=0
):
    """
    Apply 2D max pooling to input matrix.

    Parameters:
    - input_matrix: 2D numpy array (IN_ROWS x IN_COLS)
    - pool_h, pool_w: pooling window size
    - stride_h, stride_w: stride (defaults to pool size if None)
    - padding: zero padding around input; integer -> pad equally on both dims
               or ((top,bottom),(left,right)) tuple
    """
    if stride_h is None:
        stride_h = pool_h
    if stride_w is None:
        stride_w = pool_w

    # Add padding
    if padding is not None and (isinstance(padding, int) and padding > 0):
        input_matrix = np.pad(input_matrix, ((padding, padding), (padding, padding)),
                              mode="constant", constant_values=0)
    elif isinstance(padding, tuple):
        input_matrix = np.pad(input_matrix, padding, mode="constant", constant_values=0)

    in_h, in_w = input_matrix.shape
    out_h = (in_h - pool_h) // stride_h + 1
    out_w = (in_w - pool_w) // stride_w + 1

    output = np.zeros((out_h, out_w), dtype=np.float32)

    for i in range(out_h):
        for j in range(out_w):
            h_start = i * stride_h
            w_start = j * stride_w
            window = input_matrix[
                h_start: h_start + pool_h, w_start: w_start + pool_w
            ]
            output[i, j] = np.max(window)

    return output


def apply_dropout(x, dropout_p=0.5, training_mode=False, seed=None):
    """
    Apply dropout (for golden reference, we'll assume inference mode = no dropout).

    Parameters:
    - x: input array
    - dropout_p: dropout probability
    - training_mode: if True, randomly drop elements
    - seed: random seed
    """
    if training_mode:
        if seed is not None:
            np.random.seed(seed)
        mask = np.random.binomial(1, 1 - dropout_p, size=x.shape)
        return x * mask / (1 - dropout_p)
    else:
        # Inference mode - no dropout
        return x


# -----------------------------
# Config map for testbench
# -----------------------------
def matrix_type_to_code(matrix_type: str) -> int:
    """Stable encoding for matrix_type so SV can switch if needed."""
    mapping = {"random": 0, "identity": 1, "ones": 2, "small_int": 3}
    return mapping.get(matrix_type.lower(), 0)


def build_config_items_for_tb(
    *,
    n: int,
    activation_code: int,
    num_terms: int,
    pool_h: int,
    pool_w: int,
    stride_rows: int,
    stride_cols: int,
    padding: int,
    dropout_p: float,
    seed: int,
    matrix_type: str,
    value_range: tuple[float, float],
    addr_lines: int = 5,
    control_width: int = 2,
    data_width: int = 32,
    in_rows: int = 5,
    in_cols: int = 5,
    lfsr_width: int = 32,
    fifo_depth: int = 16,
    num_tests: int = 1,
) -> List[Tuple[str, int | float, str]]:
    """
    Returns an ordered list of (name, value, vtype) that maps 1:1 to MIF addresses.

    Address map (stable):
      0: NUM_TESTS (int)
      1: ACTIVATION_CODE (int, CONTROL_WIDTH LSBs)
      2: NUM_TERMS (int, ADDR_LINES LSBs)
      3: N (int)
      4: DATA_WIDTH (int)
      5: SRAM_DEPTH (int) = N*N
      6: ADDR_LINES (int)
      7: CONTROL_WIDTH (int)
      8: IN_ROWS (int)
      9: IN_COLS (int)
     10: POOL_H (int)
     11: POOL_W (int)
     12: STRIDE_ROWS (int)
     13: STRIDE_COLS (int)
     14: PADDING (int)
     15: DROPOUT_P_PERCENT (int = round(p*100))
     16: LFSR_WIDTH (int)
     17: INTERMEDIATE_BUFFER_DEPTH (int) = SRAM_DEPTH*2
     18: FIFO_DEPTH (int)
     19: SEED (int)
     20: MATRIX_TYPE (int code)
     21: MIN_VAL (float32)
     22: MAX_VAL (float32)
    """
    sram_depth = n * n
    items: List[Tuple[str, int | float, str]] = []

    def I(name, v): items.append((name, int(v), "int"))
    def F(name, v): items.append((name, float(v), "float"))

    I("NUM_TESTS", num_tests)                             # 0
    I("ACTIVATION_CODE", activation_code)                 # 1
    I("NUM_TERMS", num_terms)                             # 2
    I("N", n)                                             # 3
    I("DATA_WIDTH", data_width)                           # 4
    I("SRAM_DEPTH", sram_depth)                           # 5
    I("ADDR_LINES", addr_lines)                           # 6
    I("CONTROL_WIDTH", control_width)                     # 7
    I("IN_ROWS", in_rows)                                 # 8
    I("IN_COLS", in_cols)                                 # 9
    I("POOL_H", pool_h)                                   # 10
    I("POOL_W", pool_w)                                   # 11
    I("STRIDE_ROWS", stride_rows)                         # 12
    I("STRIDE_COLS", stride_cols)                         # 13
    I("PADDING", padding)                                 # 14
    I("DROPOUT_P_PERCENT", int(round(dropout_p * 100)))   # 15
    I("LFSR_WIDTH", lfsr_width)                           # 16
    I("INTERMEDIATE_BUFFER_DEPTH", sram_depth * 2)        # 17
    I("FIFO_DEPTH", fifo_depth)                           # 18
    I("SEED", seed if seed is not None else 0)            # 19
    I("MATRIX_TYPE", matrix_type_to_code(matrix_type))    # 20
    F("MIN_VAL", value_range[0])                          # 21
    F("MAX_VAL", value_range[1])                          # 22

    return items


# -----------------------------
# Main generator
# -----------------------------
def generate_pipeline_test_vectors(
    n=32,
    activation_type="relu",
    pool_h=2,
    pool_w=2,
    pool_padding=1,
    dropout_p=0.5,
    output_dir="testbenches",
    seed=42,
    matrix_type="random",
    value_range=(-1.0, 1.0),
    num_tests=1,
    num_terms=None,
):
    """
    Generate complete pipeline test vectors:
    Systolic Array (Matrix Mult) -> Activation (GPNAE) -> MaxPool -> Dropout
    """
    if seed is not None:
        np.random.seed(seed)

    os.makedirs(output_dir, exist_ok=True)

    # Default num_terms to full matrix size
    if num_terms is None:
        num_terms = n * n

    print("=" * 60)
    print("Generating Sienna Pipeline Test Vectors")
    print("=" * 60)

    # ========== STEP 1: Generate Input Matrices ==========
    print(f"\n1. Generating {n}x{n} input matrices...")

    if matrix_type == "identity":
        A = np.eye(n, dtype=np.float32)
        B = np.eye(n, dtype=np.float32)
    elif matrix_type == "ones":
        A = np.ones((n, n), dtype=np.float32)
        B = np.ones((n, n), dtype=np.float32)
    elif matrix_type == "small_int":
        A = np.random.randint(-3, 4, size=(n, n)).astype(np.float32)
        B = np.random.randint(-3, 4, size=(n, n)).astype(np.float32)
    else:  # random
        A = np.random.uniform(value_range[0], value_range[1], size=(n, n)).astype(np.float32)
        B = np.random.uniform(value_range[0], value_range[1], size=(n, n)).astype(np.float32)

    # ========== STEP 2: Matrix Multiplication (Systolic Array) ==========
    print(f"2. Computing matrix multiplication: C = A × B...")
    C = np.matmul(A, B).astype(np.float32)

    # ========== STEP 3: Activation Function (GPNAE) ==========
    print(f"3. Applying activation function: {activation_type}...")
    activated = apply_activation(C, activation_type)

    # ========== STEP 4: MaxPooling ==========
    print(f"4. Applying MaxPool2D (pool={pool_h}x{pool_w}, padding={pool_padding})...")

    # For simplicity, use a 5x5 region to match TB defaults IN_ROWS/IN_COLS
    in_rows, in_cols = 5, 5
    maxpool_input = activated[:in_rows, :in_cols]
    pooled = apply_maxpool_2d(
        maxpool_input,
        pool_h=pool_h,
        pool_w=pool_w,
        stride_h=pool_h,   # default to pool size; TB STRIDE_* defaults = 2
        stride_w=pool_w,
        padding=pool_padding,
    )

    # ========== STEP 5: Dropout ==========
    print(f"5. Applying Dropout (p={dropout_p}, inference mode)...")
    final_output = apply_dropout(pooled, dropout_p, training_mode=False)

    # ========== STEP 6: Write Output Files ==========
    print(f"\n6. Writing test files to '{output_dir}'...")

    # Write North Matrix (Matrix A) as MIF
    north_file = os.path.join(output_dir, "matrix_north.mif")
    write_mif_file(north_file, A)
    print(f"   ✓ {north_file} ({n}×{n} = {n*n} elements)")

    # Write West Matrix (Matrix B) as MIF
    west_file = os.path.join(output_dir, "matrix_west.mif")
    write_mif_file(west_file, B)
    print(f"   ✓ {west_file} ({n}×{n} = {n*n} elements)")

    # Write Expected Final Output as MIF
    output_file = os.path.join(output_dir, "expected_output.mif")
    write_mif_file(output_file, final_output.flatten())
    print(f"   ✓ {output_file} ({len(final_output.flatten())} elements)")

    # Write Test Configuration as MIF (FULL MAP)
    config_file = os.path.join(output_dir, "test_config.mif")
    activation_code = activation_to_code(activation_type)

    # Derive strides to mirror TB defaults (2). You can expose as CLI later.
    stride_rows = pool_h
    stride_cols = pool_w

    config_items = build_config_items_for_tb(
        n=n,
        activation_code=activation_code,
        num_terms=num_terms,
        pool_h=pool_h,
        pool_w=pool_w,
        stride_rows=stride_rows,
        stride_cols=stride_cols,
        padding=pool_padding,
        dropout_p=dropout_p,
        seed=seed,
        matrix_type=matrix_type,
        value_range=value_range,
        # constants that mirror your TB defaults
        addr_lines=5,
        control_width=2,
        data_width=32,
        in_rows=5,
        in_cols=5,
        lfsr_width=32,
        fifo_depth=16,
        num_tests=num_tests,
    )
    write_config_mif_from_items(config_file, config_items)
    print(f"   ✓ {config_file}")
    print(f"      - Wrote {len(config_items)} config words (addresses 0..{len(config_items)-1})")

    # Write intermediate results for debugging (keep as txt for readability)
    debug_file = os.path.join(output_dir, "intermediate_values.txt")
    with open(debug_file, "w") as f:
        f.write("=" * 60 + "\n")
        f.write("INTERMEDIATE VALUES (for debugging)\n")
        f.write("=" * 60 + "\n\n")

        f.write(f"Test Configuration (key fields):\n")
        f.write(f"  Number of tests: {num_tests}\n")
        f.write(f"  Activation: {activation_type} (code: 0b{activation_code:02b})\n")
        f.write(f"  Number of terms: {num_terms}\n")
        f.write(f"  Matrix size: {n}x{n}\n\n")

        f.write(f"Input Matrix A (first 3×3):\n{A[:3, :3]}\n\n")
        f.write(f"Input Matrix B (first 3×3):\n{B[:3, :3]}\n\n")
        f.write(f"After MatMul C = A×B (first 3×3):\n{C[:3, :3]}\n\n")
        f.write(f"After Activation ({activation_type}) (first 3×3):\n{activated[:3, :3]}\n\n")
        f.write(f"MaxPool Input (5×5):\n{maxpool_input}\n\n")
        f.write(f"After MaxPool:\n{pooled}\n\n")
        f.write(f"After Dropout (inference mode):\n{final_output}\n\n")

        f.write(f"Expected Final Output (first element): {final_output.flatten()[0]}\n")
        f.write(f"Expected Final Output (hex): {float_to_hex(final_output.flatten()[0])}\n")

    print(f"   ✓ {debug_file} (intermediate values for verification)")

    # ========== STEP 7: Summary ==========
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(
        f"Pipeline: MatMul -> {activation_type} -> MaxPool({pool_h}×{pool_w}) -> Dropout({dropout_p})"
    )
    print(f"Matrix size: {n}×{n}")
    print(f"Number of tests: {num_tests}")
    print(f"Activation code: 0b{activation_code:02b}")
    print(f"GPNAE terms: {num_terms}")
    print(f"Seed: {seed}")
    print(f"\nData preview:")
    print(f"  A[0,0] = {A[0,0]:.6f} (hex: {float_to_hex(A[0,0])})")
    print(f"  B[0,0] = {B[0,0]:.6f} (hex: {float_to_hex(B[0,0])})")
    print(f"  C[0,0] = {C[0,0]:.6f} (hex: {float_to_hex(C[0,0])})")
    print(f"  Final[0] = {final_output.flatten()[0]:.6f} (hex: {float_to_hex(final_output.flatten()[0])})")
    print("=" * 60)

    return {
        "A": A,
        "B": B,
        "matmul": C,
        "activated": activated,
        "pooled": pooled,
        "final": final_output,
        "config": {
            "num_tests": num_tests,
            "activation_code": activation_code,
            "num_terms": num_terms,
        },
    }


# -----------------------------
# CLI
# -----------------------------
def main():
    """Command line interface"""
    parser = argparse.ArgumentParser(
        description="Generate test vectors for Sienna pipeline"
    )
    parser.add_argument("--n", type=int, default=32, help="Matrix size (N×N)")
    parser.add_argument(
        "--activation",
        choices=["relu", "sigmoid", "tanh", "none"],
        default="relu",
        help="Activation function",
    )
    parser.add_argument("--pool-h", type=int, default=2, help="Pooling height")
    parser.add_argument("--pool-w", type=int, default=2, help="Pooling width")
    parser.add_argument("--pool-padding", type=int, default=1, help="Pooling padding")
    parser.add_argument(
        "--dropout-p", type=float, default=0.5, help="Dropout probability"
    )
    parser.add_argument(
        "--output-dir", type=str, default="testbenches", help="Output directory"
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--matrix-type",
        choices=["random", "identity", "ones", "small_int"],
        default="random",
        help="Type of input matrices",
    )
    parser.add_argument("--min-val", type=float, default=-1.0, help="Min random value")
    parser.add_argument("--max-val", type=float, default=1.0, help="Max random value")
    parser.add_argument(
        "--num-tests", type=int, default=1, help="Number of tests to run"
    )
    parser.add_argument(
        "--num-terms",
        type=int,
        default=None,
        help="Number of terms for GPNAE (default: N*N)",
    )

    args = parser.parse_args()

    generate_pipeline_test_vectors(
        n=args.n,
        activation_type=args.activation,
        pool_h=args.pool_h,
        pool_w=args.pool_w,
        pool_padding=args.pool_padding,
        dropout_p=args.dropout_p,
        output_dir=args.output_dir,
        seed=args.seed,
        matrix_type=args.matrix_type,
        value_range=(args.min_val, args.max_val),
        num_tests=args.num_tests,
        num_terms=args.num_terms,
    )


if __name__ == "__main__":
    # If run without arguments, generate default test case
    import sys

    if len(sys.argv) == 1:
        print("No arguments provided, generating default test case...")
        print("Use --help to see all options\n")
        generate_pipeline_test_vectors(
            n=32, activation_type="relu", seed=42, matrix_type="small_int", num_tests=1
        )
    else:
        main()
